### ISSUE TITLE
could you create a function to go to the origin clone or fork from source to pull updates?

### ISSUE THREAD

**Issue by shaunstanislaus** [IonicaBizau/repository-downloader#16]
could you create a function to go to the origin clone or fork from source to pull updates?

say for e.g. i clone from `foo/bar`

and it becomes `shaunstanislaus/bar`

is there anyway that it could pull form original source  and update?

i am sure you know that after you fork a repo , it doesn't get the latest update, it only get the update at the time you first fork it.

**Comment by IonicaBizau** [comment]
Well, this is probably beyond the scope of this project, but I'm sure there are small tools to do that.

On the other side, it's quite complicated to decide how to sync the changes: how would you solve the conflicts etc? 💭

**Comment by shaunstanislaus** [comment]
okay lets base on most common example that people faced.

#Example 1
https://github.com/TalAter/awesome-progressive-web-apps
I fork a repo `awesome list of progressive web apps` 
it would become `/shaunstanislaus/awesome-progressive-web-apps`
https://github.com/TalAter/awesome-progressive-web-apps 

this list is often updated by the origin source from TalAter but i am unable to update a fork clone repo of his because the remote url is not pointing to his repo.

##current solution
I have to manually add his remote url to it as origin to pull from origin master.


#Example 2
I have been starring and forking all the trending repo ever since i started using Github till today.

Is there a way that you can code 2 functions

##Function 1 - Clone all Starred Repo, which will be the original source instead of cloning forked repo

##Function 2 - Create a function that UPDATE all the `cloned starred repo` by using bash script to cd into each repo folder and do git pull, assuming if there are not changes added on to the origin repo. 
"lets put conflicts aside first and assuming that there are no changes made to the repo and its clean."

**Comment by shaunstanislaus** [comment]
@IonicaBizau you there?

**Comment by IonicaBizau** [comment]
@shaunstanislaus Sorry, I just missed this. Will take care of this soon.

**Comment by IonicaBizau** [comment]
Check out the `pull-from-source` cli tool and library: https://github.com/IonicaBizau/pull-from-source :rocket:

**Comment by shaunstanislaus** [comment]
@IonicaBizau  okay (:
