### ISSUE TITLE
warn  321 repos failed to download. Trying again.

### ISSUE THREAD

**Issue by shaunstanislaus** [IonicaBizau/repository-downloader#18]
I downloaded about 4100/5475 repositories overnight, and it hanged.

i restarted it and it skip those downloaded, and it is unable to download now.

i get this warning, any idea how to fix it?
```bash
warn  321 repos failed to download. Trying again.
```

**Comment by IonicaBizau** [comment]
That happens when the `git clone` ends with an error. Make sure you have enough space on the the disk.

When it hangs, most probably you have big repositories to download...

**Comment by shaunstanislaus** [comment]
I have 4TB space. Haha. But it's weird. Now down to 320 repos, it keeps trying at 320.

**Comment by shaunstanislaus** [comment]
Fixed.

i had to repair the harddisk tables, and it was downloading all again except those unable to download due to DMCA removed by github.

btw, i was wondering, how to do you get it to download from organisation in my account? it only download from e.g. github.com/shaunstanislaus, but doesn't download in 2 other organisations that i created and  forked some repos under.

**Comment by IonicaBizau** [comment]
> but doesn't download in 2 other organisations that i created and forked some repos under.

Maybe you are not a public member in these organizations. If so, you need to add some scopes to the token (e.g. the `repo` scope).

Glad to hear you fixed it. :grin

**Comment by shaunstanislaus** [comment]
@IonicaBizau sorry, pardon me. 

how do i add some scopes to the token?

lastly, i have some suggestions for this tool `repository-downloader` 

you know that it nicely downloads every forked repo in a folder, it would be great if you combine the pull-from-source function into here and create a script to 
1) go into this main folder where all the repos are
2) pull-from-source,
3) git push, so that all my forked repos are updated on github too instead of locally
4) once finished, script should change directory to the next repo file and do the same thing untill all its updated 1 by 1.

that would be a complete tool!  i would love to see that, would you be able to do add this nice feature to it? 💃
