### ISSUE TITLE
could you provide info for organisation downloads?

### ISSUE THREAD

**Issue by shaunstanislaus** [IonicaBizau/repository-downloader#19]
I have 2 organisations under my username `shaunstanislaus`

but i do not know how to download them from organisation, it is currently only downloading from my username that i forked, but i have other repos forked under 2 organisations i created.

could you enlighten me on that please? (:

thank you.

**Comment by IonicaBizau** [comment]
Hmm, that should be happening already. Make sure that the access token has access to read all the organizations.
