### ISSUE TITLE
Downloading private repository information?

### ISSUE THREAD

**Issue by johnhayesio** [IonicaBizau/repository-downloader#29]
I have looked to see how to do this, but either haven't found out how or it doesn't exist. My stats are only showing for public repos it seems within global-activity. Is there a way to get private repos also?

**Comment by johnhayesio** [comment]
I figured it out. The download link must be user/repos and not users/<user>/repos and it can only be done with an access token that has full repo authorization.

**Comment by johnhayesio** [comment]
Now a new problem. Although it will download all repos, the total count shown is incorrect. For instance, if you look at my Github, I have 1,869 commits in the last year. Git-stats shows that I have made 2,374 in the last year. I also have Git Streaks for mac installed and it shows the same. This is taking into account my private repos also.

**Comment by IonicaBizau** [comment]
The GitHub token should have access to the private repositories, and then the private repositories will be downloaded.

I am not sure, but maybe Git Stats counts the merge commits too...
