### ISSUE TITLE
Import from private hosts

### ISSUE THREAD

**Issue by sirwolfgang** [IonicaBizau/repository-downloader#7]
Would be nice to add private host url support. So I can import data from Stash, GitHub Enterprise, or GitLab. Obviously each of these have different implications, but would be something nice to throw under the enhancements tag.

**Comment by IonicaBizau** [comment]
I never worked with any of them... :cry: However, if you find any ways to implement this, I'd be glad to accept pull requests!

**Comment by IonicaBizau** [comment]
Like I said, I have not worked with these hosts before, but feel free to open PRs in this direction. :+1: 

Note that [`git-stats-importer 2.0.0`](https://github.com/IonicaBizau/git-stats-importer/pull/26) has an option to import all the projects located in a specific folder:

```sh
$ git-stats-importer --find-repos ~/my-projects
```

Maybe this helps. :star2:
